<a href="https://colab.research.google.com/github/jiansim03/colab/blob/main/NeuralNetwork_2output.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 항등함수와 소프트맥스 함수 구현하기
- 항등함수 : 입력을 그대로 출력한다
- 소프트맥스함수 :
(특정 뉴런의 출력값) = (해당 뉴런의 값을 지수로 하는 자연상수) / (해당 뉴런이 속한 층의 모든 뉴런 값을 지수로 넣은 자연상수)

In [5]:
import numpy as np

a = np.array([0.3, 2.9, 4.0])
exp_a = np.exp(a) # 자연상수의 지수에 a를 넣는다
print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [7]:
# 분모
sum_exp_a=np.sum(exp_a)
sum_exp_a

74.1221542101633

In [9]:
y = exp_a / sum_exp_a
y

array([0.01821127, 0.24519181, 0.73659691])

In [10]:
# 필요할 때 사용할 수 있도록 함수로 정의해놓자
def softmax(a):
  exp_a = np.exp(a) # 파라미터 값을 자연상수의 지수로 넣는다
  sum_exp_a = np.sum(exp_a)
  y = exp_a / sum_exp_a # 소프트맥스를 거친 특정 뉴런의 값
  return y

In [11]:
layer2 = np.array([0.9,2.0,1.9])
softmax(layer2)

array([0.14875534, 0.44688573, 0.40435893])

### 소프트맥스 함수 구현 시 주의점
- 소프트맥스 함수는 지수함수를 사용하므로 오버플로우 문제가 있다
- 오버플로우 : 컴퓨터는 수를 크기가 유한한 데이터로 다루므로, 너무 큰 값을 표현할 수 없는 문제
- 소프트맥스 함수에 임의의 정수 C를 곱해 해결하자

In [13]:
# 그냥 소프트맥스 함수 사용 시
a = np.array([1010, 1000,990])
np.exp(a) / np.sum(np.exp(a))

# nan값을 담은 배열이 출력. 제대로 표현되지 않는다.

<ipython-input-13-1bf8903433dd>:3: RuntimeWarning: overflow encountered in exp
  np.exp(a) / np.sum(np.exp(a))
<ipython-input-13-1bf8903433dd>:3: RuntimeWarning: invalid value encountered in true_divide
  np.exp(a) / np.sum(np.exp(a))


array([nan, nan, nan])

In [14]:
# 입력 신호 중 최대값인 C를 빼주면 올바르게 계산할 수 있다
def softmax(a) :
  c = np.max(a)
  exp_a = np.exp(a-c) # 오버플로우 대책
  sum_exp_a = np.sum(exp_a)
  y = exp_a / sum_exp_a

  return y

### 소프트맥스 함수의 특징
 - 함수의 출력은 0 ~ 1.0 사이의 실수
 - 소프트맥스 함수의 출력의 총합은 1 - 출력을 확률로 해석할 수도 있다

In [21]:
# 출력되는 값은 0~1.0 사이의 실수
a = np.array([0.3, 2.9, 4.0])
y = softmax(a)
y

array([0.01821127, 0.24519181, 0.73659691])

In [20]:
#출력의 합 = 1
np.sum(y)

1.0